---
- vars:
    - envconf: vars/dev-env.yml
  vars_files:
    - "{{ envconf }}"

  name: Provision ec2 instance in the {{ env }} environment
  connection: local
  gather_facts: False
  hosts: localhost


  tasks:
  - name: Launch or start instance
    ec2: 
      region: "{{ ec2_region }}"
      ec2_access_key: "{{ ec2key }}"
      ec2_secret_key: "{{ ec2secret }}"
      keypair: "{{ item.keypair }}"
      group: "{{ item.group }}"
      instance_type: "{{ item.instance_type }}"
      image: "{{ item.image }}"
      instance_tags: "{{ item.instance_tags }}"
      count_tag: "{{ item.count_tag }}"
      exact_count: "{{ item.exact_count}}"
      wait: true
    register: ec2
    with_items: "{{ ec2_instances }}"
