---
# Installing older docker version (non CE/EE).

- vars:
    - docker_ver: "docker-engine=1.13.1-0~ubuntu-trusty"
    - docker_apt_key: 2C52609D

  name: Provision ec2 instance
  hosts: all
  gather_facts: False
  remote_user: ubuntu
  become: true

  tasks:
  - name: setup docker.io apt repo
    apt_repository:
      repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
      state: present

  - name: check for docker.io apt key {{ docker_apt_key }}
    shell: apt-key list |grep -q {{ docker_apt_key }}
    register: result
    ignore_errors: True

#   Can't use apt-key because ub is missing python libraries...
  - name: add docker.io apt key
    command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    when: result|failed

  - name: install {{ docker_ver }}
    apt:
      name: "{{ docker_ver }}"
      update_cache: yes
      state: present

  - name: docker service running
    service:
      name: docker
      state: started
