---
# Installing older docker version (non CE/EE).

- vars:
    - docker_ver: "docker-engine=1.13.1-0~ubuntu-trusty"
    - dc_ver: 1.9.0
    - node_exp_ver: 0.14.0
    - docker_apt_key: 2C52609D
    - prometheus_root: /opt/prometheus
    - prometheus_cfg: /etc/prometheus

  name: Provision ec2 instance
  hosts: all
  gather_facts: False
  remote_user: ubuntu
  become: true

  tasks:
  - name: setup docker.io apt repo
    apt_repository:
      repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
      state: present

  - name: check for docker.io apt key {{ docker_apt_key }}
    shell: apt-key list |grep -q {{ docker_apt_key }}
    register: result
    changed_when: False
    ignore_errors: True

#   Can't use apt-key because ub is missing python libraries...
  - name: add docker.io apt key
    command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    when: result|failed

  - name: install {{ docker_ver }}
    apt:
      name: "{{ docker_ver }}"
      update_cache: yes
      state: present

  - name: docker service running
    service:
      name: docker
      state: started

  - name: create prometheus directory structure
    file: >
      state=directory
      path={{ item }}
      owner=root
      group=root
    with_items:
    - "{{ prometheus_cfg }}"
    - "{{ prometheus_root }}"
    - "{{ prometheus_root }}/dist"
    - "{{ prometheus_root }}/bin"

  - stat: path={{ prometheus_root }}/dist/node_exporter-{{node_exp_ver}}.linux-amd64.tar.gz
    register: node_exp_tar_gz

  - name: install prometheus node_exporter from tar.gz
    raw: >
      cd {{ prometheus_root }}/dist;
      wget https://github.com/prometheus/node_exporter/releases/download/v{{node_exp_ver}}/node_exporter-{{node_exp_ver}}.linux-amd64.tar.gz;
      tar xfvz node_exporter-{{node_exp_ver}}.linux-amd64.tar.gz;
      mv node_exporter-{{node_exp_ver}}.linux-amd64/node_exporter {{ prometheus_root }}/bin/;
      rm -rf node_exporter-{{node_exp_ver}}.linux-amd64;
    when: node_exp_tar_gz.stat.exists == False

  - name: create node_exporter upstart init file
    template: >
      src={{ item }}.j2
      dest=/etc/init/{{ item }}
    with_items:
      - prometheus_node_exporter.conf

  - name: start node-exporter
    service: 
      name=prometheus_node_exporter 
      state=started 
      enabled=yes

  - name: install pip
    apt:
      name: python-pip
      state: present

  - name: check for docker-compose
    shell: pip show docker-compose|grep Version
    register: result
    changed_when: False
    ignore_errors: True

  - name: pip install docker-compose
    command: pip install docker-compose=="{{ dc_ver }}"
    when: result|failed

  - name: deploy docker-compose config
    docker_service:
      project_name: wordpress
      definition:
        version: "2"
        services:
          wordpress:
            image: wordpress
            container_name: wordpress
            expose:
              - 80
            ports:
             - "80:80"
            environment:
              - WORDPRESS_DB_PASSWORD=example
            depends_on:
              - mysql
          mysql:
            image: mariadb
            container_name: mysql
            environment:
              - MYSQL_ROOT_PASSWORD=example
          cadvisor:
            image: google/cadvisor:latest
            container_name: cadvisor
            expose:
              - 8080
            ports:
              - "8080:8080"
            volumes:
              - /:/rootfs:ro
              - /var/run:/var/run:rw
              - /sys:/sys:ro
              - /var/lib/docker/:/var/lib/docker:ro
    register: output
